ecomm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", include("home.urls")),
    path("products/", include("products.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    

urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.urls import path
from home.views import index

app_name = "home"
urlpatterns = [
   path("", index, name="index")
]

products/urls.py
from django.urls import path
from products.views import detail

app_name = "products"
urlpatterns = [
   path("<slug>/", detail, name="detail")
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from products.models import Product
from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required(login_url="accounts:login")
def index(request):
    products = Product.objects.all()
    context = {
        'products': products
    }
    return render(request, "home/index.html", context)

templates/home/index.html
{% extends "base/base.html" %}

{% block body %}

<div class="container mt-5 pt-5">
    <div class="row">
        {% for product in products %}
        <div class="col-md-3">
            <figure class="card card-product-grid">
                <div class="img-wrap"> <img src="/media/{{product.product_images.first.image}}"> </div>
                <figcaption class="info-wrap border-top">
                    <a href="{% url 'products:detail' product.slug%}" class="title">{{product.product_name|slice:":30"}}...</a>
                    <div class="price mt-2">$ {{product.price}}</div> <!-- price-wrap.// -->
                </figcaption>
            </figure> <!-- card // -->
        </div> <!-- col.// -->
        {% endfor %}
    </div>
</div>
{% endblock %}