accounts/urls.py
from django.urls import path
from accounts.views import login_user, register_user, activate_account, logout_user, add_to_cart, cart, remove_cart_item, remove_coupon, payment_success

app_name = "accounts"
urlpatterns = [
    path("login/", login_user, name="login"),
    path("signup/", register_user, name="signup"),
    path("activate/<email_token>", activate_account, name="activate_account"),
    path("logout/", logout_user, name="logout"),
    path("add-cart/<uid>", add_to_cart, name="add_to_cart"),
    path("cart/", cart, name="cart"),
    path("remove-cart-item/<uid>", remove_cart_item, name="remove_cart_item"),
    path("remove-coupon/<uid>", remove_coupon, name="remove_coupon"),
    path("success/", payment_success, name="payment_success"),
]

ecomm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", include("home.urls")),
    path("products/", include("products.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    

urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.urls import path
from home.views import index

app_name = "home"
urlpatterns = [
   path("", index, name="index")
]

base/models.py
from django.db import models
import uuid

# create base class for all models


class BaseModel(models.Model):
    uid = models.UUIDField(
        primary_key=True, editable=False, default=uuid.uuid4)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

templates/base/alert.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }} {% endif %}" role="alert">
{{ message }}
</div>
{% endfor %}
{% endif %}

templates/base/base.html
<!DOCTYPE HTML>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Ecommerce</title>

    <link rel="shortcut icon" type="image/x-icon" href="/media/images/favicon.ico">

    <!-- jQuery -->
    <script src="/media/js/jquery-2.0.0.min.js" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="/media/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <link href="/media/css/bootstrap.css" rel="stylesheet" type="text/css" />

    <!-- Font awesome 5 -->
    <link href="/media/fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="/media/css/ui.css" rel="stylesheet" type="text/css" />
    <link href="/media/css/responsive.css" rel="stylesheet" />

    <!-- custom javascript -->
    <script src="/media/js/script.js" type="text/javascript"></script>

    <script type="text/javascript">
        /// some script

        // jquery ready start
        $(document).ready(function () {
            // jQuery code

        });
// jquery end
    </script>

</head>

<body>

    <header class="section-header">

        <nav class="navbar navbar-dark navbar-expand p-0 bg-dark">
            <div class="container">
                <ul class="navbar-nav d-none d-md-flex mr-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'home:index' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Delivery</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Payment</a></li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item"><a href="#" class="nav-link"> Call: +99812345678 </a></li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> English </a>
                        <ul class="dropdown-menu dropdown-menu-right" style="max-width: 100px;">
                            <li><a class="dropdown-item" href="#">Arabic</a></li>
                            <li><a class="dropdown-item" href="#">Russian </a></li>
                        </ul>
                    </li>
                </ul> <!-- list-inline //  -->
            </div> <!-- navbar-collapse .// -->
            <!-- container //  -->
        </nav> <!-- header-top-light.// -->

        <section class="header-main border-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-2 col-4">
                        <div class="brand-wrap">
                            <img class="logo" src="/media/images/logo.png">
                        </div> <!-- brand-wrap.// -->
                    </div>
                    <div class="col-lg-6 col-sm-12">
                        <form action="#" class="search">
                            <div class="input-group w-100">
                                <input type="text" class="form-control" placeholder="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form> <!-- search-wrap .end// -->
                    </div> <!-- col.// -->
                    <div class="col-lg-4 col-sm-6 col-8">
                        <div class="widgets-wrap float-md-right">
                            <div class="widget-header  mr-3">
                                <a href="{% url 'accounts:cart' %}" class="icon icon-sm rounded-circle border"><i
                                        class="fa fa-shopping-cart"></i></a>
                                <span class="badge badge-pill badge-danger notify">{{request.user.profile.get_cart_count}}</span>
                            </div>
                            <div class="widget-header icontext">
                                <a href="#" class="icon icon-sm rounded-circle border"><i class="fa fa-user"></i></a>
                                <div class="text">
                                    {% if request.user.is_authenticated %}
                                    <span class="text-muted">Welcome! {{request.user.first_name}}</span>
                                    <div>
                                        <a href="{% url 'accounts:logout' %}">Logout</a>
                                    </div>
                                    {% else %}
                                    <span class="text-muted">Welcome!</span>
                                    <div>
                                        <a href="{% url 'accounts:login' %}">Log in</a> |
                                        <a href="{% url 'accounts:signup' %}"> Register</a>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div> <!-- widgets-wrap.// -->
                    </div> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- container.// -->
        </section> <!-- header-main .// -->
    </header>


    {% block body %}
    {% endblock %}

</body>

</html>