accounts/urls.py
from django.urls import path
from accounts.views import login_user, register_user, activate_account, logout_user, add_to_cart, cart, remove_cart_item, remove_coupon, payment_success

app_name = "accounts"
urlpatterns = [
    path("login/", login_user, name="login"),
    path("signup/", register_user, name="signup"),
    path("activate/<email_token>", activate_account, name="activate_account"),
    path("logout/", logout_user, name="logout"),
    path("add-cart/<uid>", add_to_cart, name="add_to_cart"),
    path("cart/", cart, name="cart"),
    path("remove-cart-item/<uid>", remove_cart_item, name="remove_cart_item"),
    path("remove-coupon/<uid>", remove_coupon, name="remove_coupon"),
    path("success/", payment_success, name="payment_success"),
]

ecomm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", include("home.urls")),
    path("products/", include("products.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    

urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.urls import path
from home.views import index

app_name = "home"
urlpatterns = [
   path("", index, name="index")
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from base.models import BaseModel
from django.db.models.signals import post_save
from django.dispatch import receiver
import uuid
from base.emails import send_account_activation_mail
from products.models import Product, ColorVariant, SizeVariant, Coupon
from django.contrib import messages


# Create your models here.


class Profile(BaseModel):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="profile")
    profile_image = models.ImageField(upload_to="profile")
    email_token = models.CharField(max_length=100, null=True, blank=True)
    is_email_verified = models.BooleanField(default=False)


    def get_cart_count(self):
        return CartItem.objects.filter(cart__is_paid = False, cart__user=self.user).count()


class Cart(BaseModel):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="cart")
    coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL, null=True, blank=True)
    is_paid = models.BooleanField(default=False)
    razor_pay_order_id = models.CharField(max_length=100, null=True, blank=True)
    razor_pay_payment_id = models.CharField(max_length=100, null=True, blank=True)
    razor_pay_payment_signature = models.CharField(max_length=100, null=True, blank=True)



    def __str__(self) -> str:
        return f'{self.user.first_name} {self.user.last_name}'
    

    def get_total_price(self):
        price = []

        for item in self.cart_items.all():
            price.append(item.product.price)

            if item.color_variant:
                price.append(item.color_variant.price)
            if item.size_variant:
                price.append(item.size_variant.price)  

        if self.coupon:
            if sum(price) > self.coupon.minimum_amount:
                return sum(price) - self.coupon.discount_price
            else:
                self.coupon = None
                self.save()
        return sum(price)



class CartItem(BaseModel):
    cart = models.ForeignKey(
        Cart, on_delete=models.CASCADE, related_name="cart_items")
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, null=True, blank=True)
    color_variant = models.ForeignKey(
        ColorVariant, on_delete=models.SET_NULL, null=True, blank=True)
    size_variant = models.ForeignKey(
        SizeVariant, on_delete=models.SET_NULL, null=True, blank=True)
    
    def get_product_price(self):
        price = [self.product.price]

        if self.color_variant:
            price.append(self.color_variant.price)
        if self.size_variant:
            price.append(self.size_variant.price)
        
        return sum(price)


@receiver(post_save, sender=User)
def send_email_token(sender, instance, created, **kwargs):
    try:
        if created:
            email = instance.email
            email_token = str(uuid.uuid4())
            Profile.objects.create(user=instance, email_token=email_token)
            send_account_activation_mail(email, email_token)

    except Exception as e:
        print(e)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from accounts.models import Profile, Cart, CartItem
from products.models import Coupon, Product, ColorVariant, SizeVariant
import razorpay
from django.conf import settings
from django.contrib.auth.decorators import login_required
from base.helpers import save_invoice_pdf

# Create your views here.


def register_user(request):
    if request.method == "POST":
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        email = request.POST.get("email")
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")

        user_obj = User.objects.filter(username=email)

        if user_obj.exists():
            messages.error(request, "User already exist.")
            return HttpResponseRedirect(request.path)

        if password2 != password1:
            messages.error(request, "Both password must be same.")
            return HttpResponseRedirect(request.path)

        user_obj = User.objects.create(
            username=email, email=email, first_name=first_name, last_name=last_name)
        user_obj.set_password(password1)
        user_obj.save()
        messages.success(
            request, "An email has been sent on your mail to varify your email.")
        return HttpResponseRedirect(request.path)

    return render(request, "accounts/register.html")


def login_user(request):
    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')

        user_obj = User.objects.filter(username=email)

        if not user_obj.exists():
            messages.error(request, "User does not exist.")
            return HttpResponseRedirect(request.path)

        if not user_obj[0].profile.is_email_verified:
            messages.error(
                request, "User is not verified, First you need to verify by clicking the link sent to your mail.")
            return HttpResponseRedirect(request.path)

        user_obj = authenticate(username=email, password=password)

        if user_obj:
            login(request, user_obj)
            return redirect("/")
        else:
            messages.error(request, "Invalid username or password.")
            return HttpResponseRedirect(request.path)

    return render(request, "accounts/login.html")


def activate_account(request, email_token):
    try:
        user_obj = Profile.objects.get(email_token=email_token)
        user_obj.is_email_verified = True
        user_obj.save()
        return redirect("accounts:login")
    except Exception as e:
        print(e)
        return HttpResponse("<h1>Invalid token link try letter...!</h1>")


# @login_required(login_url="accounts:login")
def logout_user(request):
    try:
        logout(request)
        return redirect('home:index')
    except Exception as e:
        print(e)
        return HttpResponse("There is some error, please try leter...!")


@login_required(login_url="accounts:login")
def add_to_cart(request, uid):
    user = request.user
    product = Product.objects.get(uid=uid)
    size = request.GET.get("size")
    color = request.GET.get("color")
    cart, _ = Cart.objects.get_or_create(user=user, is_paid=False)

    cart_item = CartItem.objects.create(cart=cart, product=product)

    if size:
        size_variant = SizeVariant.objects.get(size_name=size)
        cart_item.size_variant = size_variant
        cart_item.save()
    if color:
        color_variant = ColorVariant.objects.get(color_name=color)
        cart_item.color_variant = color_variant
        cart_item.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required(login_url="accounts:login")
def cart(request):
    cart_obj = None
    try:
        cart_obj = Cart.objects.get(is_paid=False, user=request.user)
    except Exception as e:
        print(e)

    if request.method == "POST":
        coupon = request.POST.get("coupon")

        coupon_obj = Coupon.objects.filter(coupon_code=coupon)

        if not coupon_obj.exists():
            messages.error(request, "Invalid coupon code.")
            return redirect("accounts:cart")

        if cart_obj.coupon:
            messages.warning(request, "Coupon alredy applied.")
            return redirect("accounts:cart")

        if cart_obj.get_total_price() < coupon_obj[0].minimum_amount:
            messages.warning(
                request, f"Minimum amount to apply this coupon is {coupon_obj[0].minimum_amount}")
            return redirect("accounts:cart")

        if coupon_obj[0].is_expired:
            messages.warning(request, "Coupon has been expired.")
            return redirect("accounts:cart")

        cart_obj.coupon = coupon_obj[0]
        cart_obj.save()
        messages.success(request, "Coupon applied.")
        return redirect("accounts:cart")

    if cart_obj is not None:
        client = razorpay.Client(auth=(settings.KEY_ID, settings.KEY_SECRET))
        payment = client.order.create(
            {'amount': cart_obj.get_total_price()*100, 'currency': 'INR', 'payment_capture': 1})

        cart_obj.razor_pay_order_id = payment['id']
        cart_obj.save()

        context = {
            'cart': cart_obj,
            'payment': payment,
        }
    else:
        context = {
            'cart': cart_obj,
        }

    return render(request, 'accounts/cart.html', context)


@login_required(login_url="accounts:login")
def remove_cart_item(request, uid):
    try:
        cart_item = CartItem.objects.get(uid=uid)
        cart_item.delete()
    except Exception as e:
        print(e)
    return redirect("accounts:cart")


@login_required(login_url="accounts:login")
def remove_coupon(request, uid):
    cart_obj = Cart.objects.get(uid=uid)
    cart_obj.coupon = None
    cart_obj.save()

    messages.success(request, "Coupon removed.")
    return redirect("accounts:cart")


@login_required(login_url="accounts:login")
def payment_success(request):
    order_id = request.GET.get("order_id")
    payment_id = request.GET.get("payment_id")
    payment_signature = request.GET.get("payment_signature")

    cart_obj = Cart.objects.get(razor_pay_order_id=order_id)

    cart_obj.razor_pay_payment_id = payment_id
    cart_obj.razor_pay_payment_signature = payment_signature
    cart_obj.is_paid = True
    cart_obj.save()

    context = {
        'user': cart_obj.user,
        'cart':cart_obj
    }

    save_invoice_pdf(context)

    return redirect("accounts:cart")

templates/accounts/cart.html
{% extends "base/base.html" %}

{% block body %}
<section class="section-content padding-y">
    <div class="container">
        {% if cart is not None %}
        <div class="alert alert-success mt-3">
            <p class="icontext"><i class="icon text-success fa fa-truck"></i> Free Delivery within 1-2 weeks
            </p>
        </div>
        <div class="row">
            <main class="col-md-9">
                <div class="card">

                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" class="text-right" width="200"> </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in cart.cart_items.all%}
                            <tr>
                                <td>
                                    <figure class="itemside">
                                        <div class="aside"><img src="/media/{{item.product.product_images.first.image}}" class="img-sm"></div>
                                        <figcaption class="info">
                                            <a href="#" class="title text-dark">{{item.product.product_name}}</a>
                                            <p class="text-muted small">Size: {% if item.size_variant.size_name %} {{item.size_variant.size_name}}{% else %}-{% endif %}, Color: {% if item.color_variant.color_name %} {{item.color_variant.color_name}}{% else %}-{% endif %}</p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <select class="form-control">
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                    </select>
                                </td>
                                <td>
                                    <div class="price-wrap">
                                        <var class="price">${{item.get_product_price}}</var>
                                    </div> <!-- price-wrap .// -->
                                </td>
                                <td class="text-right">
                                    <a data-original-title="Save to Wishlist" title="" href="" class="btn btn-light"
                                        data-toggle="tooltip"> <i class="fa fa-heart"></i></a>
                                    <a href="{% url 'accounts:remove_cart_item' item.uid %}" class="btn btn-light"> Remove</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                    <div class="card-body border-top">
                        <button id="rzp-button1" class="btn btn-primary float-md-right"> Make Purchase <i
                                class="fa fa-chevron-right"></i> </button>
                        <a href="{% url 'home:index' %}" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Continue shopping </a>
                    </div>
                </div> <!-- card.// -->

            </main> <!-- col.// -->
            <aside class="col-md-3">
                <div class="card mb-3">
                    <div class="card-body">
                        <form method="post">
                            {% include 'base/alert.html' %}
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Have coupon?</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="coupon" placeholder="Coupon code">
                                    <span class="input-group-append">
                                        <button type="submit" class="btn btn-primary">Apply</button>
                                    </span>
                                </div>
                            </div>
                        </form>
                        {% if cart.coupon %}
                        <div>
                            <h6>Applied coupon:</h6>
                            <p class="d-flex justify-content-between"><span class="text-success font-weight-bold">{{cart.coupon.coupon_code}}</span> <a href="{% url 'accounts:remove_coupon' cart.uid %}" class="text-danger">Remove</a></p>
                        </div>
                        {% endif %}
                    </div> <!-- card-body.// -->
                </div> <!-- card .// -->
                <div class="card">
                    <div class="card-body">
                        <dl class="dlist-align">
                            <dt>Total price:</dt>
                            <dd class="text-right">USD {{cart.get_total_price}}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Discount:</dt>
                            <dd class="text-right">USD 0</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Total:</dt>
                            <dd class="text-right  h5"><strong>${{cart.get_total_price}}</strong></dd>
                        </dl>
                    </div> <!-- card-body.// -->
                </div> <!-- card .// -->
            </aside> <!-- col.// -->
        </div>
        {% else %}
        <div class="alert alert-danger mt-3">
            <p class="icontext"><i class="icon text-danget fa fa-exclamation-triangle"></i>Cart is empty.
            </p>
        </div>
        {% endif %}

    </div> <!-- container .//  -->
</section>


<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "rzp_test_yjWLHL211Bs8Oj", // Enter the Key ID generated from the Dashboard
    "amount": "{{payment.amount}}", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "INR",
    "name": "Bootstrap Ecommercer",
    "description": "Test Transaction",
    "image": "/media/images/logo.png",
    "order_id": "{{payment.id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "callback_url": "{{callback_url}}",
    "redirect": true,
    "handler": function (response){
        window.location.href = `http://127.0.0.1:8000//accounts/success?order_id=${response.razorpay_order_id}&payment_id=${response.razorpay_payment_id}&payment_signature=${response.razorpay_signature}`;
        
        
    },
    "prefill": {
        "name": "{{cart.user.first_name}} {{cart.user.last_name}}",
        "email": "{{cart.user.email}}",
        "contact": ""
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){
        alert(response.error.code);
        alert(response.error.description);
        alert(response.error.source);
        alert(response.error.step);
        alert(response.error.reason);
        alert(response.error.metadata.order_id);
        alert(response.error.metadata.payment_id);
});
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>
{% endblock %}

templates/accounts/login.html
{% extends "base/base.html" %}

{% block body %}


<!-- ============================ COMPONENT LOGIN   ================================= -->
<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
    <div class="card-body">
        <h4 class="card-title mb-4">Log in</h4>
        <form method="post">
            {% csrf_token %}
            {% include "base/alert.html" %}

            <div class="form-group">
                <input name="email" class="form-control" placeholder="Email" required type="email">
            </div> <!-- form-group// -->
            <div class="form-group">
                <input name="password" class="form-control" placeholder="Password" required type="password">
            </div> <!-- form-group// -->

            <div class="form-group">
                <a href="#" class="float-right">Forgot password?</a>
                <label class="float-left custom-control custom-checkbox"> <input type="checkbox"
                        class="custom-control-input" checked="">
                    <div class="custom-control-label"> Remember </div>
                </label>
            </div> <!-- form-group form-check .// -->
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block"> Login </button>
            </div> <!-- form-group// -->
        </form>
    </div> <!-- card-body.// -->
</div> <!-- card .// -->

<p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:signup' %}">Sign up</a></p>
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->



{% endblock %}

templates/accounts/register.html
{% extends "base/base.html" %}

{% block body %}

<!-- <section class="section-conten padding-y" style="min-height:84vh"> -->

<!-- ============================ COMPONENT REGISTER   ================================= -->
<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
    <div class="card-body">
        <h4 class="card-title mb-4">Sign Up</h4>
        <form method="post">
            {% csrf_token %}
            {% include "base/alert.html" %}

            <div class="form-group">
                <input name="first_name" class="form-control" placeholder="First Name" type="text" required>
            </div> <!-- form-group// -->
            <div class="form-group">
                <input name="last_name" class="form-control" placeholder="Last Name" type="text" required>
            </div> <!-- form-group// -->
            <div class="form-group">
                <input name="email" class="form-control" placeholder="Email" type="email" required>
            </div> <!-- form-group// -->
            <div class="form-group">
                <input name="password1" class="form-control" placeholder="Password" type="password" required>
            </div> <!-- form-group// -->
            <div class="form-group">
                <input name="password2" class="form-control" placeholder="Confirm Password" type="password" required>
            </div> <!-- form-group// -->


            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block"> Signup </button>
            </div> <!-- form-group// -->
        </form>
    </div> <!-- card-body.// -->
</div> <!-- card .// -->

<p class="text-center mt-4">Already have account? <a href="{% url 'accounts:login' %}">Log in</a></p>
<!-- ============================ COMPONENT REGISTER  END.// ================================= -->



{% endblock %}