accounts/urls.py
from django.urls import path
from accounts.views import login_user, register_user, activate_account, logout_user, add_to_cart, cart, remove_cart_item, remove_coupon, payment_success

app_name = "accounts"
urlpatterns = [
    path("login/", login_user, name="login"),
    path("signup/", register_user, name="signup"),
    path("activate/<email_token>", activate_account, name="activate_account"),
    path("logout/", logout_user, name="logout"),
    path("add-cart/<uid>", add_to_cart, name="add_to_cart"),
    path("cart/", cart, name="cart"),
    path("remove-cart-item/<uid>", remove_cart_item, name="remove_cart_item"),
    path("remove-coupon/<uid>", remove_coupon, name="remove_coupon"),
    path("success/", payment_success, name="payment_success"),
]

ecomm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", include("home.urls")),
    path("products/", include("products.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    

urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.urls import path
from home.views import index

app_name = "home"
urlpatterns = [
   path("", index, name="index")
]

products/urls.py
from django.urls import path
from products.views import detail

app_name = "products"
urlpatterns = [
   path("<slug>/", detail, name="detail")
]

products/models.py
from typing import Iterable, Optional
from django.db import models
from django.db.models import CharField

from base.models import BaseModel
from django.utils.text import slugify


# Create your models here.


class Category(BaseModel):
    category_name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, blank=True, null=True)
    category_image = models.ImageField(upload_to="category")

    def save(self, *args, **kwagrs):
        self.slug = str(slugify(self.category_name))
        return super(Category, self).save(*args, **kwagrs)

    def __str__(self) -> str:
        return self.category_name


class ColorVariant(BaseModel):
    color_name = models.CharField(max_length=100)
    price = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.color_name


class SizeVariant(BaseModel):
    size_name = models.CharField(max_length=100)
    price = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.size_name


class Product(BaseModel):
    product_name = models.CharField(max_length=100)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="product")
    slug = models.SlugField(unique=True, blank=True, null=True)
    product_description = models.TextField()
    price = models.IntegerField()
    color_variant = models.ManyToManyField(ColorVariant, blank=True)
    size_variant = models.ManyToManyField(SizeVariant, blank=True)

    def save(self, *args, **kwargs):
        self.slug = str(slugify(self.product_name))
        return super(Product, self).save(*args, **kwargs)

    def __str__(self) -> CharField:
        return self.product_name

    def get_product_price_by_variant(self, size, color):
        size_price = 0
        color_price = 0
        if SizeVariant.objects.filter(size_name=size):
            size_price = SizeVariant.objects.filter(size_name=size)[0].price
        if ColorVariant.objects.filter(color_name=color):
            color_price = ColorVariant.objects.filter(color_name=color)[0].price

        return self.price + size_price + color_price


class ProductImage(BaseModel):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="product_images")
    image = models.ImageField(upload_to="product")


class Coupon(BaseModel):
    coupon_code = models.CharField(max_length=15)
    is_expired = models.BooleanField(default=False)
    discount_price = models.IntegerField(default=100)
    minimum_amount = models.IntegerField(default=500)

    def __str__(self) -> str:
        return self.coupon_code

products/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from products.models import Product, SizeVariant, ColorVariant
from accounts.models import Cart, CartItem
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required(login_url="accounts:login")
def detail(request, slug):
    try:
        product = Product.objects.get(slug=slug)
        context = {
            'product': product
        }

        if request.method == "GET":
            size = request.GET.get("size", "")
            color = request.GET.get("color", "")
            price = product.get_product_price_by_variant(size, color)
            context['updated_price'] = price
            context['selected_size'] = size
            context['selected_color'] = color

    except Exception as e:
        print(e)
    return render(request, "products/detail.html", context)

templates/products/detail.html
{% extends "base/base.html" %}

{% block body %}
<section class="section-content padding-y bg">
    <div class="container">

        <!-- ============================ COMPONENT 1 ================================= -->
        <div class="card">
            <div class="row no-gutters">
                <aside class="col-md-6">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap">
                            <div> <a href="#"><img src="/media/{{product.product_images.first.image}}"></a></div>
                        </div> <!-- slider-product.// -->
                        <div class="thumbs-wrap">
                            {% for image in product.product_images.all %}
                            <a href="#" class="item-thumb"> <img src="/media/{{image.image}}"></a>
                            {% endfor %}

                        </div> <!-- slider-nav.// -->
                    </article> <!-- gallery-wrap .end// -->
                </aside>
                <main class="col-md-6 border-left">
                    <article class="content-body">

                        <h2 class="title">{{product.product_name}}</h2>

                        <div class="rating-wrap my-3">
                            <ul class="rating-stars">
                                <li style="width:80%" class="stars-active">
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </li>
                                <li>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </li>
                            </ul>
                            <small class="label-rating text-muted">132 reviews</small>
                            <small class="label-rating text-success"> <i class="fa fa-clipboard-check"></i> 154
                                orders </small>
                        </div> <!-- rating-wrap.// -->

                        <div class="mb-3">
                            {% if updated_price %}
                            <var class="price h4">${{updated_price}}</var>
                            {% else %}
                            <var class="price h4">${{product.price}}</var>
                            {% endif %}
                        </div> <!-- price-detail-wrap .// -->

                        <p>{{product.product_description}}</p>


                        <dl class="row">
                            <dt class="col-sm-3">Model#</dt>
                            <dd class="col-sm-9">Odsy-1000</dd>

                            <dt class="col-sm-3">Color</dt>
                            <dd class="col-sm-9">Brown</dd>

                            <dt class="col-sm-3">Delivery</dt>
                            <dd class="col-sm-9">Russia, USA, and Europe </dd>
                        </dl>

                        <hr>
                        <div class="form-row">
                            <div class="form-group col-md flex-grow-0">
                                <label>Quantity</label>
                                <div class="input-group mb-3 input-spinner">
                                    <div class="input-group-append">
                                        <button class="btn btn-light" type="button" id="button-minus"> − </button>
                                    </div>
                                    <input type="text" class="form-control" value="1">
                                    <div class="input-group-prepend">
                                        <button class="btn btn-light" type="button" id="button-plus"> + </button>
                                    </div>

                                </div>
                            </div> <!-- col.// -->
                            {% if product.color_variant.count %}
                            <div class="form-group col-md">
                                <label>Select Color</label>
                                <div class="mt-1">
                                    {% for color in product.color_variant.all %}
                                    <label class="custom-control custom-radio custom-control-inline">
                                        <input type="radio" name="select_color" {% if selected_color == color.color_name %} checked  {% endif %} onchange="get_currect_price('{{color.color_name}}', '{{selected_size}}')" class="custom-control-input">
                                        <div class="custom-control-label">{{color.color_name}}</div>
                                    </label>
                                    {% endfor %}
                                </div>
                            </div> <!-- col.// -->
                            {% endif %}

                            {% if product.size_variant.count %}
                            <div class="form-group col-md">
                                <label>Select size</label>
                                <div class="mt-1">
                                    {% for size in product.size_variant.all %}
                                    <label class="custom-control custom-radio custom-control-inline">
                                        <input type="radio" name="select_size" {% if selected_size == size.size_name %} checked  {% endif %}
                                            onchange="get_currect_price('{{selected_color}}', '{{size.size_name}}')"
                                            class="custom-control-input">
                                        <div class="custom-control-label">{{size.size_name}}</div>
                                    </label>
                                    {% endfor %}
                                </div>
                            </div> <!-- col.// -->
                            {% endif %}
                        </div> <!-- row.// -->

                        <a href="#" class="btn  btn-primary"> Buy now </a>
                        <a href="{% url 'accounts:add_to_cart' product.uid %}?size={{selected_size}}&color={{selected_color}}" class="btn  btn-outline-primary"> <span class="text">Add to cart</span> <i
                                class="fas fa-shopping-cart"></i> </a>
                    </article> <!-- product-info-aside .// -->
                </main> <!-- col.// -->
            </div> <!-- row.// -->
        </div> <!-- card.// -->
        <!-- ============================ COMPONENT 1 END .// ================================= -->


    </div>
</section>

<script>
    function get_currect_price(color="", size="") {
        window.location.href = window.location.pathname + `?size=${size}&color=${color}`
    }
</script>
{% endblock %}